language: python

python:
  - 2.7

before_install:
  - git config --global push.default matching
  - git config --global user.name "aimer1124"
  - git config --global user.email "380774061@qq.com"


install:
  - pip install scrapy

script:
  - cd data
  - scrapy crawl themes -o ./data/theme_data.csv
  - cd ..

after_success:
  - git init
  - git add --all .
  - git commit -m "Auto Builder From Travis"
  - git push --quiet --force https://$DEPLOY_REPO@github.com/aimer1124/hexo-theme-spider master